### ISSUE TITLE
Can't get sample to run

### ISSUE THREAD

**Issue by nikmartin** [jspears/bobamo#16]
Possibly node 0.10 blows everything up, but includes on Schema names don't work. I have to include the actual file - still working to get it going

**Comment by nikmartin** [comment]
also:
loading  /home/nmartin/downloaded-projects/bobamo/plugins/jsonschema/jsonschema.js
error loading plugin [/home/nmartin/downloaded-projects/bobamo/plugins/jsonschema/jsonschema.js] { [Error: Cannot find module 'swagger-node-express/Common/node/paramTypes'] code: 'MODULE_NOT_FOUND' }

error loading plugin [/home/nmartin/downloaded-projects/bobamo/plugins/csvimport/csvimport.js] { [Error: Cannot find module 'q'] code: 'MODULE_NOT_FOUND' }

One of these two errors may be why the UI is busted. it sort of loads, but no css, just raw html

**Comment by nikmartin** [comment]
This ios probably why the page won;t render.  Loading /less gives a 500 error:

```
Express
500 TypeError: Cannot read property 'length' of null
at SendStream.hasTrailingSlash (/home/nmartin/downloaded-projects/bobamo/node_modules/connect/node_modules/send/lib/send.js:171:36)
at SendStream.pipe (/home/nmartin/downloaded-projects/bobamo/node_modules/connect/node_modules/send/lib/send.js:316:27)
at static (/home/nmartin/downloaded-projects/bobamo/node_modules/connect/lib/middleware/static.js:84:8)
at callbacks (/home/nmartin/downloaded-projects/bobamo/node_modules/express/lib/router/index.js:161:37)
at /home/nmartin/downloaded-projects/bobamo/lib/plugin-api.js:138:21
at callbacks (/home/nmartin/downloaded-projects/bobamo/node_modules/express/lib/router/index.js:161:37)
at param (/home/nmartin/downloaded-projects/bobamo/node_modules/express/lib/router/index.js:135:11)
at pass (/home/nmartin/downloaded-projects/bobamo/node_modules/express/lib/router/index.js:142:5)
at nextRoute (/home/nmartin/downloaded-projects/bobamo/node_modules/express/lib/router/index.js:100:7)
at callbacks (/home/nmartin/downloaded-projects/bobamo/node_modules/express/lib/router/index.js:164:11)
```

**Comment by jspears** [comment]
Can u try the pre-1.0 branch I think it's fixed there

Sent from my iPhone

On Jun 14, 2013, at 8:20 PM, Nik Martin notifications@github.com wrote:

This ios probably why the page won;t render. Loading /less gives a 500
error:

Express
500 TypeError: Cannot read property 'length' of null
at SendStream.hasTrailingSlash
(/home/nmartin/downloaded-projects/bobamo/node_modules/connect/node_modules/send/lib/send.js:171:36)
at SendStream.pipe
(/home/nmartin/downloaded-projects/bobamo/node_modules/connect/node_modules/send/lib/send.js:316:27)
at static (/home/nmartin/downloaded-projects/bobamo/node_modules/connect/lib/middleware/static.js:84:8)
at callbacks (/home/nmartin/downloaded-projects/bobamo/node_modules/express/lib/router/index.js:161:37)
at /home/nmartin/downloaded-projects/bobamo/lib/plugin-api.js:138:21
at callbacks (/home/nmartin/downloaded-projects/bobamo/node_modules/express/lib/router/index.js:161:37)
at param (/home/nmartin/downloaded-projects/bobamo/node_modules/express/lib/router/index.js:135:11)
at pass (/home/nmartin/downloaded-projects/bobamo/node_modules/express/lib/router/index.js:142:5)
at nextRoute (/home/nmartin/downloaded-projects/bobamo/node_modules/express/lib/router/index.js:100:7)
at callbacks (/home/nmartin/downloaded-projects/bobamo/node_modules/express/lib/router/index.js:164:11)

—
Reply to this email directly or view it on
GitHubhttps://github.com/jspears/bobamo/issues/16#issuecomment-19488147
.

**Comment by nikmartin** [comment]
Just did - it all comes crashing down because of 1 missing file: /bobamo/plugins/less/less/media.less
 I wget-ted  the copy in less' github, and it's trying to start, but is just grinding away on my Schemas - not sure what's up.  I'll fetch clean and try again

**Comment by nikmartin** [comment]
FYI your package.jsons in pre1.0 are ancient

**Comment by nikmartin** [comment]
pre1.0 crashes also. What I did was git pull a fresh copy, switch to pre1.0 branch, git pull again, the npm install failed due to out of date dependencies, so I just switched all dependencies to latest, npm install, then npm link, then:

```
nmartin@mockbook:~/downloaded-projects/bobamo/examples/simple$ node app.js 
bobamo plugins /home/nmartin/downloaded-projects/bobamo/examples/simple/plugins
path.existsSync is now called `fs.existsSync`.
loading  /home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/bobamo/plugins/passport/passport.js
error loading plugin [/home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/bobamo/plugins/passport/passport.js] { [Error: Cannot find module 'passport-local'] code: 'MODULE_NOT_FOUND' }
loading  /home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/bobamo/plugins/imageupload/imageupload.js
error loading plugin [/home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/bobamo/plugins/imageupload/imageupload.js] { [Error: Cannot find module 'fs-extra'] code: 'MODULE_NOT_FOUND' }
loading  /home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/bobamo/plugins/static/static.js
loading  /home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/bobamo/plugins/appeditor/appeditor.js
loading  /home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/bobamo/plugins/modeleditor/modeleditor.js
loading  /home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/bobamo/plugins/less/less.js
loading  /home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/bobamo/plugins/generator/generator.js
loading  /home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/bobamo/plugins/rest/rest.js
loading  /home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/bobamo/plugins/mongoose/mongoose.js
loading  /home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/bobamo/plugins/package/package.js
did not load plungin [jsonschema]
did not load plungin [csvimport]
did not load plungin [renderer]
did not load plungin [passport]
did not load plungin [imageupload]
did not load plungin [acl]
Public Dir:  /home/nmartin/downloaded-projects/bobamo/examples/simple/public
public dirs /home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/bobamo/plugins/appeditor/public /home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/bobamo/public/plugins/appeditor
public dirs /home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/bobamo/plugins/modeleditor/public /home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/bobamo/public/plugins/modeleditor
public dirs /home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/bobamo/plugins/less/public /home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/bobamo/public/plugins/less
jsConfig /js/config/appeditor.js
base /modeleditor
jsConfig /js/config/modeleditor.js
jsConfig /js/config/less.js
reading  /home/nmartin/downloaded-projects/bobamo/examples/simple/conf/bobamo.json
mounted bobamo on  
listening on 3001
TypeError: Object #<Object> has no method 'template'
    at Function.exports.jqtpl.render (/home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/consolidate/lib/consolidate.js:366:12)
    at /home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/consolidate/lib/consolidate.js:144:25
    at /home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/consolidate/lib/consolidate.js:97:5
    at fs.js:252:14
    at Object.oncomplete (fs.js:93:15)
```

**Comment by nikmartin** [comment]
From error in: bobamo/examples/simple/node_modules/bobamo/plugins/imageupload/node_modules/fs-extra
So I tried to run npm install in the module and got:

```
npm http 404 https://registry.npmjs.org/jquery.ui.widget
npm http 200 https://registry.npmjs.org/ncp
npm http GET https://registry.npmjs.org/ncp/-/ncp-0.4.2.tgz
npm ERR! 404 'jquery.ui.widget' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.8.2-201303270829
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/nmartin/downloaded-projects/bobamo/examples/simple/node_modules/bobamo/plugins/imageupload
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.27
npm ERR! code E404

```

**Comment by nikmartin** [comment]
I've thrown in the towel for now, I just can't seem to get it running, there's just too many broken dependencies for me to deal with.  Maybe when you get a more stable release I'll try again

**Comment by oori** [comment]
I know this is antik, but I recently came back to this due to an application upgrade.  
The solution to your issue:  `TypeError: Object #<Object> has no method 'template'`  is to force jqtpl to version 1.x  in your package.json.     this issue is not related to bobamo, but with consolidate.js (which isn't compatible with jqtpl v2.x)
