### ISSUE TITLE
Actions accumulation

### ISSUE THREAD

**Issue by oori** [jspears/bobamo#7]
For example:
1. Click on "Delete" of some document (in the Model table)
2. Click "Cancel"
3. Do this (1+2) again on another document. 
The onCancel event just fired for twice...    (and the accumulation goes on until refresh..).

But, a worst example:  Delete a document, and then another one.  That would try to delete the old one again (you can look at your console log, and the network requests).
That example crashed bobamo before this Mers commit (https://github.com/oori/mers/commit/91c96863bfcc30d886ac8dcfb6163665f134d3bf)

I'm not sure where it originates, but it's quite obvious what the problem it's all around bobamo.

Thanks.

**Comment by jspears** [comment]
This is probable due to not cleaning up all the views when a view is destroyed.  Most of the actions are using delegated events, if something matches, even if it isn't what was originally intended it matches and fires.   Will do a cleanup making sure that bobamo does not do this.

**Comment by oori** [comment]
I looked at it, but I didn't saw exactly where it happens in the code...   You should be able to see it,  just start deleting objects, and look at your console - you'll see it accumulating and reissuing "old" calls.
Thanks.

**Comment by oori** [comment]
Thanks.
This is still an issue with Delete actions.      very simple to see:
1. delete object A  --> everything OK  (one restful DELETE is sent)
2. delete object B  --> boom.   (it sends two DELETEs, first for A, and then for B)

I guess you don't notice this because of the bug in Mers,   I sent you a pull request on that some time ago:
https://github.com/jspears/mers/pull/4

Thanks again.

**Comment by oori** [comment]
I just saw it in another place.   It is "not important",  but I guess they all are related.
1. On a Passport protected bobamo,  you get the login page.
2. before logging in,  click a couple of times on different items (object types) in the menu.   It will not let you through, and keep you in the login form.
3. put in username/password, and submit.
4. you'll see it jump through the clicks in #2 ....

Maybe there are more places with this accumulation around?    I'll check and let you know.
Thanks again.

**Comment by jspears** [comment]
OK, I think I fixed at least part of this problem.    confirm_change had el:'body', which apparently attached its listeners to the body.   This was a mistake on my part, due to a misunderstanding of how backbone works.   I changed it so that it appends itself to the 'body' if it is not already attached to the dom.      I am not sure it is the same problem you see with passport.

Playing around with the auth, not sure if it is related or fixed or I am not seeing the problem.    I am not entirely sure this and the delete issues are related.

**Comment by oori** [comment]
I can confirm that the "delete accumulation" is now resolved.   Thanks !

As for the "post-login accumulation" - that's there.  the simplest way to see it is as I explained above, and open you dev-tool's "Network" tab - you'll see all the calls..   BUT - this 'bug' is really **not important**.
